scrape_configs:
  - job_name: service-a
    scrape_interval: 4s
    static_configs:
      - targets: ['service-a:5000']

  - job_name: service-b
    scrape_interval: 4s
    static_configs:
      - targets: ['service-b:5001']
    metric_relabel_configs:
      - source_labels: [__name__]
        separator: ;
        regex: traefik_router_(requests_tls_total|request_duration_seconds.*|open_connections|requests_bytes_total|responses_bytes_total)
        replacement: $1
        action: drop
          
      # drop everything except 429's
      - source_labels: [__name__, code]
        separator: ;
        #regex: traefik_router_requests_total;(?:[^4][0-9][0-9]|4(?:[0-1]|[3-9])[0-8]|42[0-8]|4(?:[0-1]|[3-9])9|0)
        #regex: traefik_router_requests_total;(?:[^4][0-9][0-9]|4(?:[0-1]|[3-9])[0-8]|42[0-8]|4(?:[0-1]|[3-9])9)
        regex: traefik_router_requests_total;(?:[125][0-9][0-9]|4(?:[0-1]|[3-9])[0-8]|42[0-8]||4(?:[0-1]|[3-9])9|0)
        replacement: $1
        action: drop

## removes traefik_service_requests_total
#      - source_labels: [__name__, code]
#        separator: ;
#        #regex: traefik_router_requests_total;(?:429)|(?:3[0-9].*)
#        regex: traefik_router_requests_total;(?:3[0-9].*|(?:429))
#        replacement: $1
#        action: keep
#

          #  (?:[125][0-9][0-9])   # match 1xx,2xx,5xx
